// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	_ "net/http/pprof"

	"github.com/comeonjy/go-kit/pkg/xlog"
	"github.com/comeonjy/go-layout/configs"
	data2 "github.com/comeonjy/go-layout/internal/infrastructure/data"
	"github.com/comeonjy/go-layout/internal/server"
	"github.com/comeonjy/go-layout/internal/service"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, logger *xlog.Logger) *App {
	configsInterface := configs.NewConfig(ctx)
	dataData := data2.NewData(configsInterface)
	workRepo := data2.NewWorkRepo(dataData)
	schedulerService := application.NewSchedulerService(configsInterface, logger, workRepo)
	grpcServer := server.NewGrpcServer(schedulerService, configsInterface, logger)
	httpServer := server.NewHttpServer(ctx, configsInterface, logger, schedulerService)
	app := newApp(ctx, grpcServer, httpServer, configsInterface)
	return app
}
