// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"context"
	"github.com/comeonjy/go-kit/pkg/xlog"
	"github.com/comeonjy/go-layout/configs"
	"github.com/comeonjy/go-layout/internal/domain/aggregate"
	"github.com/comeonjy/go-layout/internal/infra/persistence"
	"github.com/comeonjy/go-layout/internal/server"
	"github.com/comeonjy/go-layout/internal/service"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitApp(ctx context.Context, logger *xlog.Logger) *App {
	configsInterface := configs.NewConfig(ctx)
	data := persistence.NewData(configsInterface)
	workRepo := persistence.NewWorkRepo(data)
	workUseCase := aggregate.NewWorkUseCase(workRepo)
	schedulerService := service.NewSchedulerService(configsInterface, logger, workUseCase)
	grpcServer := server.NewGrpcServer(schedulerService, configsInterface, logger)
	httpServer := server.NewHttpServer(ctx, configsInterface, logger, schedulerService)
	app := newApp(ctx, grpcServer, httpServer, configsInterface)
	return app
}
